site_name: Programming and social science

nav:
  - Home: index.md
  - Setup: setup.md

theme:
  name: material
  custom_dir: overrides
  logo: logo.png

extra_css:
  - stylesheets/extra.css

plugins: []

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
